server:
  name: Golang Fiber Simple Project
  port: 8000
  logger: true
  prefork: false

database:
  driver: mysql
  url: root:123456aA@@tcp(localhost:3306)/simple?parseTime=True
  migrate: true
  logger: true

jwt:
  secretKey: "my-32-character-secret@access_token"
  accessToken:
    expiredAt: 1440
  refreshToken:
    expiredAt: 2880